apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: newshosting
  namespace: media
spec:
  encryptedData:
    password: AgBvxc/f73eb1bKMvMTUuCvqLknwuft2JI73cZ/wlVSKsuuFZP+zy0vGxRVoqCidPhH7mWZi+6991w7ilV/L8ww/Fuy7qEJV4+XNGMJc8K0mcG9uXZQYJD57tTp28LQP8yAvhph4iQH9HaTfPVDDzxgpQh+jZalKt6clbMR3kttk+ykTgflmjN89dfQhR8a299crXrKVqllYnmIfQa+kHgwiaBCdUJ/He3ilk4njdqBYLBkQdwIP8Lgn+QxJlMAIP9q82LUa0BcaPSzTcoRpMJoJstk2dUTwdf7SxwqgsF75aIajPPHtOaRCO7dhFYf3i+8CeSwKRUsG2AvgjFZBrjwuRFWJGA6pRZaFg8M/IG9cBWwk369eVy7NfGa92qCnTPHWuNNIl9I3AZ8BMNSSkMKeUP6vKAM7Fm4Dx7qXVI4j58MDDDckX/9bKyCjnQ27TV60ysVZgMwvHCRa77ETPq3YOArZxleiRz2EogSbSZYmcCzh689Sf8loJCejVj1XR1/KZdaL5e2EB+qqvXzNADEoWGUdI7QG+sD7z9amCkMjfsbdnrloTubbv1BfSQcWe+xR2uaYMP2TFbF2OJ7YYe1IvMOk3dwmqQ1DgRry4yRXIb0GAyel6VmdQYeg4PDl+e9/2D5cgp5yTgInKe5TA7WY19vQftg+54toYd1TWOTMIwjSrk7N9buFjIOefY4gT+/7P8CSwcUiXG3iNvyQ9A==
    username: AgBZ/F9v/+yZhcwAoL46ysQbJYY3SJA/gSNIfSgPFKjSPhZBi0P0hEwZ0ZeUxhoiAlxpFzO2p5Xd6NjqU1YVfA4tQ4qOlJaOwCK00vbm5TE4j0QDEy8zB4SoyAxH1aMBE9qFXggXVFGKWVC0jv7rc4Lb+DF0Q0B2IqMMJ5FoB16rpNK/94VBys0TWQAEaB3jX2BHM4PvPtiAlYJmR9jdlu8GA3sjDb8ZMJ1kKOIXZjGbUjt+99hXGXKchrKz/zsvN81wLjtIlCOkofz3WEGEBO4qXJz0zosR8WY0H1G3YBBZph6A/cs2kbH9uIijqS3gDTd3w383LPXl3lc3gWW+4J/GKjzp7mvzoYYhVA1eX+vkiCL5oIR+NzMrDZfWFNHuPXZmi4XGIbr12eWjN3Aj/6vMp5iyvTKMPfM2loFhSHrwkMWsTd3TLz1RkI6so87gC+jAJ/WuZLd+QFwQ/yIDw7d4T9JDpr16BVEgWclVK2OkyHhhqaDzFSNFzlvnBrRBM0LWZ1C8+6N67Xr5MRP5wKlR9PhvhrUtwIPTJqgGowOALan1mBJddhRNo1IaXQRp1U6fK28Q+6f60oMRs+XTPbJo/K6acGAii9TAEk65f+oMFsg8/WCm/9em9kPEKLZ6ChPtTz2zK6cO5WfgmM8BaYa2gHEO3xnQFqBFbYtb+EziEiy8fT3bN/EAutoWQ+QqjOrmLPxCDuKY1A==
  template:
    metadata:
      name: newshosting
      namespace: media
    type: Opaque
