apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-tailscale
  namespace: media
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - jellyfin
  rules:
    - host: jellyfin
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-tailscale
  namespace: media
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - sonarr
  rules:
    - host: sonarr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sonarr
                port:
                  number: 8989
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-tailscale
  namespace: media
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - radarr
  rules:
    - host: radarr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  number: 7878
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nzbget-tailscale
  namespace: media
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - nzbget
  rules:
    - host: nzbget
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nzbget
                port:
                  number: 6789
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission-tailscale
  namespace: media
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - transmission
  rules:
    - host: transmission
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transmission
                port:
                  number: 9091
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett-tailscale
  namespace: media
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - jackett
  rules:
    - host: jackett
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jackett
                port:
                  number: 9117
