apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nzbgeek
  namespace: media
spec:
  encryptedData:
    apiKey: AgBgN250xThE8JGWL6l9GS1VmlGy7mtzydL6IR3lNzC3/FL/rRe0w7oVcLcrOFVMKDoAd4GmEEs8xfsY3ci2QZtolZSTPpdtWTJYogGYszJ8cDSUUt1PsbOmMx4hHU2Q+Wu2O/zyEqHqmuFPYA4oigLUADCRmsBgah1qdjl/YacDtzOIDY4+xUSGkcFxXMneZU7X1e80jlqUSCiLfUVvfwos9/TPXoUYBT3R8XTeSFzBBQ42lmGh+KMSR+9NtX3zReEYbfvbuRUse2amaOtkMoxGipGcdQ5FsXYKwbyOzwNZcYooSBHbbMKSOmxRaR0ZwZpJ8wk+dXcppS/XsCQAlgCQOC3Q8fNjQd9t5ew0kbECJSci0PVdJFmgwPpdR1zhcmDPV31LKE/gGVELZGjNrpqOhNBdmAvo4s+M4Iq0qDVxQOzppTe4GMO+0l2r/hCnpETICv5e6i/ur2H0+/9XsZCuVQmPtN64MM7uZm22Gg+XuimfViFyvB+mmPHwh8p5kLgv9aCPa3hhRkk0r+2RAzrjNOF9rA+fxjG7ny7ph4+FFhoPLgRgQcRAUf0k3kCSLujJvEJWEIJWqV8dKlALMprqmxs94JENmyXeo9z0PGAmvyVFWEHxr2soFy+k40L45wcHx6LuEG8TPm2v5FRHGSeP+z1b2H5hkV41IO0vw0Sc69/mu06GJ0OmYZVhUUaVZS2/RpmESHVKJlft/Bl3QanHC5EW3KpE4Aa9AtoNtQijYA==
  template:
    metadata:
      name: nzbgeek
      namespace: media
    type: Opaque
