// Package iroh is the in-house Go binding for iroh (n0-computer/iroh-ffi
// 1.1.0), generated by uniffi-bindgen-go. iroh_ffi.go and iroh.h are
// GENERATED — regenerate with `nix run .#iroh-go-regen`; edit only this
// file by hand.
//
// Linking: the generated code does not carry linker flags. This file adds
// the library name and the per-OS system libraries; the library search
// path is left to the build (CGO_LDFLAGS="-L<dir with libiroh_ffi.a>"),
// which is what nix/default.nix sets. See ../README.md for the static /
// musl / cross-compile story.
package iroh

// #cgo LDFLAGS: -liroh_ffi
// #cgo darwin LDFLAGS: -framework Security -framework SecurityFoundation -framework SystemConfiguration -framework CoreWLAN -framework Foundation -framework CoreFoundation -lobjc -liconv
// #cgo linux LDFLAGS: -lm -ldl -lpthread
import "C"
