apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCPA8D6n4DcDJTCh8HFTrsjafH7VfELvbqttOGY5opznFro844PW0yV0xD9ldP2Jp2MsD0zI6+yI96QOIuqHYHTi4Nyg4zQkvaInuVEOKJ4KYNZSHnW/+jgGGi8mKQF4mxsO6q9aBfkgopG2fI8Y1ZtNh5PdO0snpVjCTPtJO37hsoJGWQtjza3bGvFL+B2hgTCyOjL+s66D0Sc7WBAV/khifyAU6uW1KYw6QKAAyMkuLq0hc54IT+Hy2yYK2+rZTEnHVOw1clxexpt+Q3z1Vn+a6E+9yJqoEiA9oOCKEKcKMc0QXVE+MN5JeV7bp+sAhSeLHDcApvf6eTYtROV/OBUTh64MkqCPWnoZvKLElmcPaFZeG15Csi/YiBIGshhKmoBXekHUHbbGbvB9qJh4qMGvPKmucuqriDYr17UWo0wkgB+qlU5prXtLW+68VZMfdF1yNpciSi9WM2pvGpt2VQYekFDr6NIonDyQmQnA4ocxdeLGaozx8sJ7ZW2FJ81LFt151cvdWoEMJScOC+ykl/tYrYAG4wkoE1fA2NoG8LjqfRVJZ5Cvo5zYTPUWSE6ZD/zRFzQ410ZojuE4YCOmhJP3O856ShktbJH3sDVfiLivdrK4Agy/CMumrpBd7SIEU4JpZjGa7NdIakuCM/4gKLOKL9sSZih1deDRiYK72bw+YVSivoNA4x8XBsRoI+BNws36U32iZw4PQGqs5kEs1fZxg==
    client_secret: AgAt2P6YTQ2Q/DWZEfaT9ohBQVcf8k52SrBQtAjL+hPo/oDOMznwnBpJuYiaaaMzCTaUeddcEMadld+NLAJ4PiArv1smRzoG6P6B5ue1+Ffl2u6jnUHH2hgrQDEKP8pahhcy16XqRDh4hdxYpPoztF7EpgN/gxWygUSU1kzZURxrCWtdxnb7dr+Be5mLVYr3LHChbeZywi7H+fxvX1aBv6CSyt7jVKVypkaD+k0ClecaVZJsVDTgR8B9W5Ui5OdEqkNVhG5+X4CvP4r2b77a/1FmjQUEjLIRjW9TcbC1M9VnVdTjAidZNVGkIzIS1Ej1JMI7PllLxKE+Y85Z3aAwqIqRJ2DHunTDHjkFEh3dXdEwrzg0rz4XLjLL0wD8qyuXvwpjr0+Y+3PXx4gGzvhFDd8NO6dBG/PjKzMOXKfu7eIIwVocBYwysL4t2TOKMjk+Awbop5JhGIxwcSyURdScECKFNWgzE9PQDdUx0JMxG9JCUN45y7RV7ejJ/8DWZc6L8K59nleB03SDRzr0nWS6xC+TT8LyvZJInk/bBWOOscM6xQhTf40/w+vCSbRwyzHlSdLM7rAVVbb+b/gToBKiatpR9gDOR2ndB8q4jxitQZ0uE/KFbG1x3HPczNMyAlA1annpj65C6JIhcfNepbDW7U37CDTLCo2bqcF0qTWOWnOL8AA5DWNJg84bs23K5KnVPssf8Mjj63FQTLJKFyKZw/w+Aa4QNsIM2hBY15iZsLj2jvhhevs5ffoePccqwssd7LupP0qKzhw8RR7aJpZKepO5
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
